### PR TITLE
system: config hugepage and SPDK related kernel module

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
Related issue: https://github.com/harvester/harvester/issues/5274
This PR is the prerequisites for longhorn v2 engine support.

Included:
- hugepage setup
- related kernel module

### CODE REVIEW

**Review by ibrokethecloud — APPROVED** [review]
lgtm. thanks.

**Comment by Vicente-Cheng** [comment]
pending until we create `harvester-v1.3.x` branch

**Review by brandboat — APPROVED** [review]
LGTM ! Huge thanks !!!

Tested in harvester master branch
```
harvester-node-0:~ # cat /proc/meminfo | grep 'HugePages_'
HugePages_Total:    1024
HugePages_Free:     1024
HugePages_Rsvd:        0
HugePages_Surp:        0

harvester-node-0:~ # kubectl get node harvester-node-0 -o yaml | yq '.status.capacity' | grep 'hugepages'
hugepages-1Gi: "0"
hugepages-2Mi: 2Gi
```

**Comment by Vicente-Cheng** [comment]
Still pending until v1.4.0

**Review by tserong — COMMENTED** [review]
I've tested this and it works fine. My one reservation is that https://www.kernel.org/doc/html/latest/admin-guide/mm/hugetlbpage.html says "Pages that are used as huge pages are reserved inside the kernel and cannot be used for other purposes". I take this to mean that every node in a Harvester cluster won't be able to use that 2GiB of RAM for anything other than Longhorn. If that's true, we'd really only want this to be applied if and only if the v2 engine were enabled.

**Comment by tserong** [comment]
I've handled this differently in https://github.com/harvester/node-manager/pull/55 so that the config is dynamically generated based on whether the v2 engine is enabled on each node.

**Comment by Vicente-Cheng** [comment]
Thanks, @tserong. We can close it because we will have a new mechanism for it.

**Pull request closed without merging**
