### PR TITLE
audit: enable auditd by default

### PR DESCRIPTION
**Pull request by tjjh89017**
related to https://github.com/harvester/harvester-installer/pull/306

Signed-off-by: Date Huang <date.huang@suse.com>

### CODE REVIEW

**Comment by bk201** [comment]
The elemental approach is to use `systemctl` to enable services

https://rancher.github.io/elemental-toolkit/docs/reference/cloud_init/#stagesstage_idstep_namesystemctl

**Comment by tjjh89017** [comment]
I changed it to systemctl style in /system/oem
tks a lot

**Review by bk201 — APPROVED** [review]
LGTM

**Review by Vicente-Cheng — APPROVED** [review]
LGTM

**Review by guangbochen — APPROVED** [review]

**Pull request merged**
