### PR TITLE
Add fio for benchmark test

### PR DESCRIPTION
**Pull request by guangbochen**
**Description:**
Add fio for the benchmark test.

### CODE REVIEW

**Comment by guangbochen** [comment]
btw @johnliu55tw can u please help to add the `fio` tool with the next OS change, maybe in the rebase work, thanks.

**Comment by bk201** [comment]
@tjjh89017 Could we verify the tool is included in SLES?

**Comment by tjjh89017** [comment]
sle-micro-rancher has fio package.
I will update baseOS to include this package.

**Comment by bk201** [comment]
@tjjh89017 helped include the fio package in the new OS now: https://build.opensuse.org/package/rdiff/isv:Rancher:Harvester:BaseOS/baseos?linkrev=base&rev=3

Let's still merge this one, we'll keep this branch for OpenSUSE variant.

**Review by bk201 — APPROVED** [review]

**Pull request merged**
