### PR TITLE
OS: update BaseOS to SLE-for-Rancher 5.3

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
- remove the NetworkManager
    - Add back the Wicked
    - Manually add sysvinit-tools (for command fsync)
    - Add k9s on OBS and remove the k9s installation from luet

Signed-off-by: Vicente Cheng <vicente.cheng@suse.com>

### CODE REVIEW

**Comment by bk201** [comment]
Here is the OBS repo: https://build.opensuse.org/package/show/isv:Rancher:Harvester:BaseOS53/baseos

**Comment by Vicente-Cheng** [comment]
I would add harvester-installer CI to let `baseos` could test with the fresh installation.

**Comment by masteryyh** [comment]
LGTM, tested with building an ISO with new base OS:
```
harv:/home/rancher # cat /etc/os-release
NAME="SLE Micro"
VERSION="5.3"
VERSION_ID="5.3"
PRETTY_NAME="Harvester d8783e4-dirty"
ID="sle-micro-rancher"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.3"
VARIANT="Harvester"
VARIANT_ID="Harvester-20230130-8de8a4d"
GRUB_ENTRY_NAME="Harvester d8783e4-dirty"
```

```
harv:/home/rancher # zypper search -i NetworkManager
Loading repository data...
Warning: No repositories defined. Operating only with the installed resolvables. Nothing can be installed.
Reading installed packages...
No matching items found.
```

```
harv:/home/rancher # zypper search -i wicked
Loading repository data...
Warning: No repositories defined. Operating only with the installed resolvables. Nothing can be installed.
Reading installed packages...

S  | Name           | Summary                                                | Type
---+----------------+--------------------------------------------------------+--------
i+ | wicked         | Network configuration infrastructure                   | package
i  | wicked-service | Network configuration infrastructure - systemd service | package
```

**Review by masteryyh — APPROVED** [review]
LGTM, tested with building an ISO with new base OS:

```
harv:/home/rancher # cat /etc/os-release
NAME="SLE Micro"
VERSION="5.3"
VERSION_ID="5.3"
PRETTY_NAME="Harvester d8783e4-dirty"
ID="sle-micro-rancher"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.3"
VARIANT="Harvester"
VARIANT_ID="Harvester-20230130-8de8a4d"
GRUB_ENTRY_NAME="Harvester d8783e4-dirty"
```

```
harv:/home/rancher # zypper search -i NetworkManager
Loading repository data...
Warning: No repositories defined. Operating only with the installed resolvables. Nothing can be installed.
Reading installed packages...
No matching items found.
```

```
harv:/home/rancher # zypper search -i wicked
Loading repository data...
Warning: No repositories defined. Operating only with the installed resolvables. Nothing can be installed.
Reading installed packages...

S  | Name           | Summary                                                | Type
---+----------------+--------------------------------------------------------+--------
i+ | wicked         | Network configuration infrastructure                   | package
i  | wicked-service | Network configuration infrastructure - systemd service | package
```

**Review by bk201 — APPROVED** [review]
LGTM

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
