### PR TITLE
config: change the root label checking from COS_ACTIVE to COS_STATE

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
- We introduce the new elemental-toolkit. There is a main change
      for the root label from COS_ACTIVE to COS_STATE so we need to
      change the related checking.

### CODE REVIEW

**Review by bk201 — APPROVED** [review]

**Comment by bk201** [comment]
LGTM, It would be nice to have a PR description.

**Comment by Vicente-Cheng** [comment]
> LGTM, It would be nice to have a PR description.

Thanks for the reminder! updated!

**Review by masteryyh — APPROVED** [review]
LGTM, thanks

**Comment by Vicente-Cheng** [comment]
@Mergifyio backport harvester-v1.2.x

**Pull request merged**
