### PR TITLE
build: add syntax for local build

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
Related issue: https://github.com/harvester/harvester/issues/6027

    - we need to define syntax for local build

### CODE REVIEW

**Comment by Vicente-Cheng** [comment]
Depends on the request https://build.opensuse.org/request/show/1181467

~After that, we need to remove the packages we do not need.~

Packages are handled on OBS side

**Comment by Vicente-Cheng** [comment]
After that, we need to remove the packages we do not need.

**Review by bk201 — APPROVED** [review]

**Review by tserong — APPROVED** [review]
LGTM, but why do we need to do this? I mean, what effect does this change have?

**Comment by Vicente-Cheng** [comment]
> LGTM, but why do we need to do this? I mean, what effect does this change have?

Hi @tserong,
Thanks for the question, I updateed more on the commit message.
This syntax is used to make docker build work due to the line `ARCH=${TARGETPLATFORM#linux/}`.

**Comment by tserong** [comment]
Thanks @Vicente-Cheng !

**Comment by Vicente-Cheng** [comment]
@mergifyio backport harvester-v1.2.x harvester-v1.3.x

**Pull request merged**
