### PR TITLE
Update for v1.2.x

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
Related to https://github.com/harvester/harvester/issues/3587

### CODE REVIEW

**Review by bk201 — APPROVED** [review]
lgtm

**Review by masteryyh — APPROVED** [review]
LGTM, thanks

**Review by bk201 — APPROVED** [review]

**Comment by bk201** [comment]
To wait for elemental bump to the latest version and create this PR on master first.

**Comment by Vicente-Cheng** [comment]
Hi @bk201, @masteryyh
This PR is ready to review again. Please help to check it, thanks!

**Review by bk201 — APPROVED** [review]
LGTM, thanks

**Review by masteryyh — APPROVED** [review]

**Pull request merged**
