### PR TITLE
os-release: keep SLE's os-release and append variants

### PR DESCRIPTION
**Pull request by bk201**
Keep what SLE micro provides:
```
NAME="SLE Micro"
VERSION="5.2"
VERSION_ID="5.2"
PRETTY_NAME="SUSE Linux Enterprise Micro for Rancher 5.2"
ID="sle-micro-rancher"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.2"
```

and append [VARIANTS](https://www.freedesktop.org/software/systemd/man/os-release.html#General%20information%20identifying%20the%20operating%20system) to the end:
```
VARIANT="Harvester"
VARIANT_ID="Harvester-20220622"
```

### CODE REVIEW

**Comment by tjjh89017** [comment]
It probably will break the support bundle kit.
Should we add new os support for the support bundle collector?

https://github.com/rancher/support-bundle-kit/blob/master/hack/support-bundle-collector.sh#L18

**Comment by bk201** [comment]
Nice spot. It certainly breaks.
I feel it's sane to keep the original file. (Although we need to change the PRETTY_NAME for upgrade use in the installer). Any objection to adding the support on the support bundle side?

**Comment by tjjh89017** [comment]
> Nice spot. It certainly breaks. I feel it's sane to keep the original file. (Although we need to change the PRETTY_NAME for upgrade use in the installer). Any objection to adding the support on the support bundle side?

If we keep ID=harvester, we don't need to modify anything.
but if so, we should consider to have a new way to determine OS flavor?

**Comment by bk201** [comment]
https://github.com/rancher/support-bundle-kit/pull/39 should address this.
Add `sle-micro-rancher` collector. We can add more rules on the support bundle side if needed.

**Review by tjjh89017 — APPROVED** [review]
LGTM

**Comment by tjjh89017** [comment]
If we kept the ID=harvester, and we don't need to modify support bundle kit.

If ID will be changed, we should have a new way to determine the "harvester" in collector script.
________________________________
寄件者: Kiefer Chang ***@***.***>
寄件日期: Wednesday, June 22, 2022 2:25:20 PM
收件者: harvester/os2 ***@***.***>
副本: Date Huang ***@***.***>; Review requested ***@***.***>
主旨: Re: [harvester/os2] os-release: keep SLE's os-release and append variants (PR #41)


Nice spot. It certainly breaks.
I feel it's sane to keep the original file. (Although we need to change the PRETTY_NAME for upgrade use in the installer). Any objection to adding the support on the support bundle side?

**Pull request merged**
