### PR TITLE
Bump rancherd to v0.1.0-rc3

### PR DESCRIPTION
**Pull request by starbops**
Able to download and install the CA file retrieved from Rancher automatically during the join-node process.

### CODE REVIEW

**Review by bk201 — APPROVED** [review]
LGTM

**Review by Vicente-Cheng — APPROVED** [review]
LGTM!

**Comment by bk201** [comment]
@mergifyio backport harvester-v1.2.x

**Comment by bk201** [comment]
@mergifyio backport harvester-v1.2.x

**Pull request merged**
