### PR TITLE
ssh: update harvester config

### PR DESCRIPTION
**Pull request by tjjh89017**
add additional harvester configs

Signed-off-by: Date Huang <date.huang@suse.com>

### CODE REVIEW

**Comment by bk201** [comment]
AllowTcpForwarding: just wondering if there is a benefit to keeping this one, perhaps users might want to port-forward to their VMs (those only have mgmt network).

**Comment by tjjh89017** [comment]
> AllowTcpForwarding: just wondering if there is a benefit to keeping this one, perhaps users might want to port-forward to their VMs (those only have mgmt network).

We should suggest those users use Service and NodePort to forward VM.

**Comment by bk201** [comment]
> > AllowTcpForwarding: just wondering if there is a benefit to keeping this one, perhaps users might want to port-forward to their VMs (those only have mgmt network).
> 
> We should suggest those users use Service and NodePort to forward VM.

That makes sense, thanks.

**Review by Vicente-Cheng — APPROVED** [review]
LGTM!

**Review by bk201 — APPROVED** [review]
LGTM

**Pull request merged**
